### PR TITLE
Update meadow.config.yaml with new network config

### PR DESCRIPTION
**Pull request by adrianstevens**

### CODE REVIEW

**Comment by NevynUK** [comment]
`Options allow enabling debug builds or controlling JIT compilation (`--jit` to enable [default], `--interp` to disable).`

I would not mention `--jit` as it is the default anyway.

`NtpRefreshPeriod` has been changed to `NtpRefreshPeriodSeconds` to make it clear that the period is measured in seconds.

**Comment by adrianstevens** [comment]
Thanks @NevynUK - PR updated

**Review by NevynUK — APPROVED** [review]
Looks good to me.

**Review by CartBlanche — APPROVED** [review]
LGTM

**Pull request merged**
